// src/constants/stlCatalogData.ts
// Auto-generated full STL catalog imported from SCAT (vtx.in.ua/scat) with full Georgian descriptions.

export interface ScatStlItem {
  id: string;
  title: string;
  type: string;
  frame: string;
  author: string;
  image: string;
  downloadUrl: string;
  date: string;
  description: string;
  material?: string;
  walls?: number;
  infill?: string;
  supports?: string;
  vtxMount?: string;
}

export const SCAT_STL_CATALOG: ScatStlItem[] = [
  {
    "id": "scat-1",
    "title": "VTX დამჭერი უნივერსალური (25x35x6 მმ)",
    "type": "VTX დამჭერი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/25w_35h_6d_30.5_20_vtx_holder v14.webp",
    "downloadUrl": "https://stl.vtx.in.ua/25w_35h_6d VTX holder.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-2",
    "title": "VTX დამჭერი Mark4 V2 (19x35x6 მმ)",
    "type": "VTX დამჭერი",
    "frame": "Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/19w_35h_6d_30.5_20_vtx_holder v3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/19w_35h_6d VTXholder.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-3",
    "title": "VTX დამჭერი Mark4 (19x25x6 მმ)",
    "type": "VTX დამჭერი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/19w_25h_6d_30.5_20_vtx_holder v3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/19w_25h_6d_30.5_20_vtx_holder v3.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-4",
    "title": "VTX დამჭერი Apex HD (32x20x6 მმ)",
    "type": "VTX დამჭერი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/32w_20h_6d_30.5_20_vtx_holder v6.webp",
    "downloadUrl": "https://stl.vtx.in.ua/32w_20h_6d_30.5_20_vtx_holder v6.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-5",
    "title": "VTX დამჭერი XL10 v6 (25x29x5 მმ)",
    "type": "VTX დამჭერი",
    "frame": "XL10 v6",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/25w_29h_5d_30.5_20_vtx_holder v1.webp",
    "downloadUrl": "https://stl.vtx.in.ua/25w_29h_5d_30.5_20_vtx_holder v1.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-6",
    "title": "VTX დამჭერი Mark4 V2 / Thor T67 (19x35x6 მმ)",
    "type": "VTX დამჭერი",
    "frame": "Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/19w_35h_6d_41_20_vtx_holder v3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/19w_35h_6d_41_20_vtx_holder v3.stl.zip",
    "date": "2026-03-15",
    "description": "მოდელირებულია Thor T67-ისთვის, თუმცა თავსებადია ნებისმიერ VTX-თან 41.5x30.5 ან 20x20 მმ სამაგრის სტანდარტით. RX დამჭერი მოყვება ცალკე ფაილად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 20x20, 41.5x30.5.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "20x20, 41.5x30.5"
  },
  {
    "id": "scat-7",
    "title": "VTX დამჭერი VT40 (22x30x5 მმ)",
    "type": "VTX დამჭერი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/22w_30h_5d_30.5_20_vtx_holder_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/22w_30h_5d_30.5_20_vtx_holder.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-8",
    "title": "VTX დამჭერი VT40 (24.5x24.5x5 მმ)",
    "type": "VTX დამჭერი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/22w_30h_5d_30.5_20_vtx_holder_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/24.5w_24.5h_5d_30.5_20 vtx holder.zip",
    "date": "2026-03-15",
    "description": "შექმნილია Dec1 (Spot) SMA ვერსიისთვის, თუმცა იდეალურად ერგება ყველა VTX-ს 30.5x30.5 ან 20x20 მმ სამაგრებით. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5, 20x20.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5, 20x20"
  },
  {
    "id": "scat-9",
    "title": "VTX დამჭერი 30.5x30.5 + SMA (VT40)",
    "type": "VTX დამჭერი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Pidor 30x30 square vtx holder v13.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Pidor 30x30 square vtx holder v13.stl",
    "date": "2026-03-15",
    "description": "მოდელირებულია AKK TX3000AC ვიდეოგადამცემისთვის, თუმცა ერგება მსგავსი გაბარიტებისა და 30.5x30.5 სამაგრის მქონე VTX-ებს.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა, სამაგრი ხვრელები: 30.5x30.5.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა",
    "vtxMount": "30.5x30.5"
  },
  {
    "id": "scat-10",
    "title": "VTX დამჭერი Rush Max Solo + SMA (VT40)",
    "type": "VTX დამჭერი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Pidor max solo vtx holder v2.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Pidor max solo vtx holder v2.stl",
    "date": "2026-03-15",
    "description": "შექმნილია Rush Max Solo-სთვის, მაგრამ ერგება სხვა მსგავსი ზომის მძლავრ VTX-ებს. ანტენის სამაგრი უნივერსალურია და გათვლილია Aeronetix 1700-2700 ანტენაზე.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-11",
    "title": "VTX დამჭერი Peak / KaraFPV კუდზე (F10)",
    "type": "VTX დამჭერი",
    "frame": "F10",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/peak_kara_vtx_mount_f10.webp",
    "downloadUrl": "https://stl.vtx.in.ua/peak_kara_vtx_mount_f10.zip",
    "date": "2026-03-15",
    "description": "მოდელი შედგება 2 ნაწილისგან: VTX-ის დამჭერი და ანტენის დამჭერი, რათა ვიბრაციების დროს ანტენამ კონექტორი არ დააზიანოს. ანტენა ფიქსირდება პლასტმასის მომჭერებით (ხამუთებით / Zip-ties). შემუშავებულია F10 ჩარჩოსთვის (სვეტებს შორის მანძილი 14 მმ), თუმცა საჭიროების შემთხვევაში მარტივად ერგება სხვა ჩარჩოებსაც.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა, სამაგრი ხვრელები: 41.5x30.5.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა",
    "vtxMount": "41.5x30.5"
  },
  {
    "id": "scat-12",
    "title": "VTX დამჭერი tailVTX MAXSOLO (Mark4)",
    "type": "VTX დამჭერი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Mark4 tailVTX_2.5W.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Mark4 tailVTX_2.5W.stl",
    "date": "2026-03-15",
    "description": "ზოგავს დიდ ადგილს ჩარჩოს შიგნით და ანტენას მაღლა სწევს უკეთესი რადიოკავშირისა და დაფარვის მისაღწევად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-13",
    "title": "VTX ანტენის სამაგრი Rush Max Solo (VT40)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Хвіст_PD_Rush_Solo_Max.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Хвіст_PD_Rush_Solo_Max.zip",
    "date": "2026-03-15",
    "description": "ქვედა ფენა 2 შრე. გარე ბრიმი (Brim) 5 მმ. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: Elastan D70, შევსება: 15%, კედლები: 2, საყრდენები (Supports): კი.",
    "material": "Elastan D70",
    "walls": 2,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-14",
    "title": "VTX ანტენის სამაგრი Rush Tank Solo (VT40)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Хвіст_solo_tank.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Хвіст_solo_tank.zip",
    "date": "2026-03-15",
    "description": "ქვედა ფენა 2 შრე. გარე ბრიმი (Brim) 5 მმ. RX მიმღების დამჭერი მოყვება ცალკე ფაილად + გადამყვანები მის გარეშე მონტაჟისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: Elastan D70, შევსება: 15%, კედლები: 2, საყრდენები (Supports): კი.",
    "material": "Elastan D70",
    "walls": 2,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-15",
    "title": "VTX ანტენის სამაგრი SMA (Mark4)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Sma antenna holder.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Sma antenna holder.stl",
    "date": "2026-03-15",
    "description": "მოდელირებულია PETG პლასტიკისთვის. მაგრდება უშუალოდ ჩარჩოს ზედა ფირფიტაზე.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-16",
    "title": "VTX ანტენის სამაგრი Caddx Vista (Apex HD)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/ApexHD_VistaAntennaMount.webp",
    "downloadUrl": "https://raw.githubusercontent.com/Pancronos/FPV-3D-print/main/ImpulseRC/Apex/ApexHD_VistaAntennaMount.STL",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: TPU, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "TPU",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-17",
    "title": "VTX ანტენის სამაგრი (F10)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "F10",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/VTX_Stock_Antenna_Mount_STPHobby_10X_.webp",
    "downloadUrl": "https://stl.vtx.in.ua/VTX_Stock_Antenna_Mount_STPHobby_10X_.STL",
    "date": "2026-03-15",
    "description": "ბეჭდვა შესაძლებელია ნებისმიერი პლასტიკით, თუმცა საუკეთესო შედეგს იძლევა მოქნილი TPU 95A ან Elastan.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: Elastan D100, შევსება: 50%, კედლები: 3, საყრდენები (Supports): კი.",
    "material": "Elastan D100",
    "walls": 3,
    "infill": "50%",
    "supports": "კი"
  },
  {
    "id": "scat-18",
    "title": "VTX ანტენის უნივერსალური სამაგრი უკანა სვეტებზე (19-32 მმ)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Universal_VTX_holder v7.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Universal_VTX_holder v7.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-19",
    "title": "VTX და RX ანტენის კომბინირებული სამაგრი (HGLRC Nblade)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/hglrc nblade vtx mount.webp",
    "downloadUrl": "https://stl.vtx.in.ua/hglrc nblade vtx mount.stl",
    "date": "2026-03-15",
    "description": "სპეციალურად შექმნილია HGLRC Nblade ჩარჩოსთვის. აერთიანებს VTX და RX ანტენების საიმედო ფიქსაციას.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-20",
    "title": "სადესანტო ფეხები 5 სმ (Mark4 / V2)",
    "type": "სადესანტო ფეხები",
    "frame": "Mark4 / Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/mark4 leg 5cm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/mark4 leg 5cm.stl",
    "date": "2026-03-15",
    "description": "Mark4 და Mark4 V2 ჩარჩოების სადესანტო ფეხები (5 სმ). შესაძლებელია გამოყენება სხვა ჩარჩოებზეც მსგავსი სხივებით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-21",
    "title": "სადესანტო ფეხები 10 სმ (Mark4 / V2)",
    "type": "სადესანტო ფეხები",
    "frame": "Mark4 / Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/mark4 leg 10cm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/mark4 leg 10cm.stl",
    "date": "2026-03-15",
    "description": "Mark4 და Mark4 V2 ჩარჩოების სადესანტო ფეხები (10 სმ). შესაძლებელია გამოყენება სხვა ჩარჩოებზეც მსგავსი სხივებით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-22",
    "title": "სადესანტო ფეხები 12 სმ (Mark4 / V2)",
    "type": "სადესანტო ფეხები",
    "frame": "Mark4 / Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/mark4 leg 12cm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/mark4 leg 12cm.stl",
    "date": "2026-03-15",
    "description": "Mark4 და Mark4 V2 ჩარჩოების სადესანტო ფეხები (12 სმ). შესაძლებელია გამოყენება სხვა ჩარჩოებზეც მსგავსი სხივებით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-23",
    "title": "სადესანტო ფეხები 15 სმ (Mark4 / V2)",
    "type": "სადესანტო ფეხები",
    "frame": "Mark4 / Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/mark4 leg 15cm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/mark4 leg 15cm.stl",
    "date": "2026-03-15",
    "description": "Mark4 და Mark4 V2 ჩარჩოების სადესანტო ფეხები (15 სმ). შესაძლებელია გამოყენება სხვა ჩარჩოებზეც მსგავსი სხივებით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 6, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 6,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-24",
    "title": "სადესანტო დემპფერ-ფეხები 5 სმ",
    "type": "სადესანტო ფეხები",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/FPV Dempfer 5sm v14.webp",
    "downloadUrl": "https://stl.vtx.in.ua/FPV Dempfer 5sm v14.step",
    "date": "2026-03-15",
    "description": "ზედა და ქვედა მთლიანი ფენები 1 მმ სისქით. რეკომენდებულია ბეჭდვა ჰორიზონტალურ მდგომარეობაში (მწოლიარე).\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 40%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "40%",
    "supports": "არა"
  },
  {
    "id": "scat-25",
    "title": "სადესანტო ფეხები Mavic 3",
    "type": "სადესანტო ფეხები",
    "frame": "Mavic 3",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_legs_Mavic3_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_legs_Mavic3.zip",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 40%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "40%",
    "supports": "კი"
  },
  {
    "id": "scat-26",
    "title": "სადესანტო ფეხები Autel EVO Max 4T",
    "type": "სადესანტო ფეხები",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_leg_Autel_EVO_Max_4T_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_leg_Autel_EVO_Max_4T.zip",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 40%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "40%",
    "supports": "კი"
  },
  {
    "id": "scat-27",
    "title": "GPS სამაგრი 18x18 მმ (Apex HD)",
    "type": "GPS სამაგრი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/18x18_gps_Apex_mount.webp",
    "downloadUrl": "https://stl.vtx.in.ua/18x18_gps_Apex_mount.stl",
    "date": "2026-03-15",
    "description": "გათვლილია 18x18 მმ ზომის GPS მოდულის (მაგ. BN-180 / BN-220) საიმედო მონტაჟისთვის ჩარჩოს ზედა ფირფიტაზე ხრახნებით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-28",
    "title": "GPS სამაგრი 18x18 მმ (Mark4)",
    "type": "GPS სამაგრი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/18x18_gps_Mark4_mount.webp",
    "downloadUrl": "https://stl.vtx.in.ua/18x18_gps_Mark4_mount.stl",
    "date": "2026-03-15",
    "description": "გათვლილია 18x18 მმ ზომის GPS მოდულის (მაგ. BN-180 / BN-220) საიმედო მონტაჟისთვის ჩარჩოს ზედა ფირფიტაზე ხრახნებით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-29",
    "title": "სადესანტო ფეხები VT40",
    "type": "სადესანტო ფეხები",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor leg v2.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor leg v2.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-30",
    "title": "RX ანტენის სამაგრი ძრავის ქვეშ (19x19 მმ)",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Motor RX holder.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Motor RX holder.stl",
    "date": "2026-03-15",
    "description": "მაგრდება ძრავის 19x19 მმ სამაგრ ხვრელებზე. მონტაჟდება გამამაგრებელი წიბოებით ქვემოთ.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-31",
    "title": "RX ანტენის უნივერსალური სამაგრი უკანა სვეტებზე (19-32 მმ)",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Universal_RX_holder.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Universal_RX_holder.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-32",
    "title": "RX ანტენის სამაგრი სხივზე",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/rx_arm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_ANT_mount/rx_arm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-33",
    "title": "RX ანტენის სამაგრი — ვერტიკალური პოლარიზაცია (ELRS)",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/ELRS vertical leg.webp",
    "downloadUrl": "https://stl.vtx.in.ua/ELRS vertical leg.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-34",
    "title": "RX ანტენის სამაგრი ძრავის ქვეშ (19x19 მმ)",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_rx_holder_motor.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_rx_holder_motor.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-35",
    "title": "RX ანტენის სამაგრი კორპუსზე v1",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_rx_holder_body_v1.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_rx_holder_body_v1.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-36",
    "title": "RX ანტენის სამაგრი კორპუსზე v2",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_rx_holder_body_v2.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_rx_holder_body_v2.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-37",
    "title": "RX ანტენის ვერტიკალური ანძა",
    "type": "RX ანტენის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/vertical mast short_02.webp",
    "downloadUrl": "https://stl.vtx.in.ua/vertical mast short_02.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 100%, კედლები: 1, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 1,
    "infill": "100%",
    "supports": "არა"
  },
  {
    "id": "scat-38",
    "title": "კამერის სამაგრი 19 მმ (VT40)",
    "type": "კამერის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Pidor camera holder 27mm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Pidor camera holder 27mm.stl",
    "date": "2026-03-15",
    "description": "კამერის სამაგრი 19 მმ ზომისთვის. სიმაღლე 30 მმ, სვეტებს შორის მანძილი 27 მმ.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-39",
    "title": "კამერის სამაგრი 19 მმ (VT40 / Kemp)",
    "type": "კამერის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/camholder_WT40_19mm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Кронштейн камери_WT40_19mm.STL",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-40",
    "title": "კამერის სამაგრი 20 მმ (VT40)",
    "type": "კამერის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/camholder_WT40_20мм.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Кронштейн камери_WT40_20мм.STL",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-41",
    "title": "კამერის სამაგრი 19 მმ (VT40)",
    "type": "კამერის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_vt40_19.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_vt40_19.STL",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-42",
    "title": "კამერის სამაგრი 22 მმ (VT40)",
    "type": "კამერის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_vt40_22.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_vt40_22.STL",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-43",
    "title": "კამერის სამაგრი 26 მმ (VT40)",
    "type": "კამერის სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_vt40_26.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_vt40_26.STL",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-44",
    "title": "Caddx 384 თერმოკამერის სამაგრი სხივზე (XL10 v6)",
    "type": "კამერის სამაგრი",
    "frame": "XL10 v6",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/caddx 384 arm holder v13.webp",
    "downloadUrl": "https://stl.vtx.in.ua/caddx 384 arm holder v13.zip",
    "date": "2026-03-15",
    "description": "დაპროექტებულია XL10 v6 / v7 ჩარჩოსთვის, თუმცა ერგება სხვა ჩარჩოებსაც სხივის მსგავსი სიგანით. არქივში მოცემულია რამდენიმე ცალკეული დეტალი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-45",
    "title": "კამერის სამაგრი 19 მმ (Mark4)",
    "type": "კამერის სამაგრი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/v1_19mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/v1_19mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-46",
    "title": "კამერის სამაგრი 22 მმ (Mark4)",
    "type": "კამერის სამაგრი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/v1_22mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/v1_22mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-47",
    "title": "კამერის სამაგრი 19 მმ (Mark4 V2)",
    "type": "კამერის სამაგრი",
    "frame": "Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/v2_19mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/v2_19mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-48",
    "title": "კამერის სამაგრი 22 მმ (Mark4 V2)",
    "type": "კამერის სამაგრი",
    "frame": "Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/v2_22mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/v2_22mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-49",
    "title": "კამერის სამაგრი 19 მმ (XL10 v6)",
    "type": "კამერის სამაგრი",
    "frame": "XL10 v6",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/XL10V6_19mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/XL10V6_19mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-50",
    "title": "კამერის სამაგრი 22 მმ (XL10 v6)",
    "type": "კამერის სამაგრი",
    "frame": "XL10 v6",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/XL10V6_22mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/XL10V6_22mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-51",
    "title": "კამერის სამაგრი 19 მმ (Apex HD)",
    "type": "კამერის სამაგრი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/apex_19mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/apex_19mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-52",
    "title": "კამერის დაგრძელებული სამაგრი 19 მმ (Apex HD)",
    "type": "კამერის სამაგრი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/apex_19mm_long.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/apex_19mm_long.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-53",
    "title": "კამერის სამაგრი 22 მმ (Apex HD)",
    "type": "კამერის სამაგრი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/apex_22mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/apex_22mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-54",
    "title": "კამერის დაგრძელებული სამაგრი 22 მმ (Apex HD)",
    "type": "კამერის სამაგრი",
    "frame": "Apex HD",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/apex_22mm_long.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_CAMERA_MOUNT/Static/apex_22mm_long.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-55",
    "title": "კამერის სამაგრი სხივზე (Mark4 V2)",
    "type": "კამერის სამაგრი",
    "frame": "Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Camera arm holder. Mark4 v2.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Camera arm holder. Mark4 v2.stl",
    "date": "2026-03-15",
    "description": "მონიშვნა \"M\" მიმართულია ძრავისკენ, \"S\" — სტეკისკენ. კამერის ფიქსაციისთვის დამატებით საჭიროა სამაგრი რკალი და ორი ხრახნი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-56",
    "title": "კამერის დაგრძელებული სამაგრი 22 მმ (Mark4)",
    "type": "კამერის სამაგრი",
    "frame": "Mark4",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Mark4_v1_22mm camera holder_pic1.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Mark4_v1_22mm camera holder.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-57",
    "title": "კამერის სამაგრი 19 მმ (24x35x6 მმ)",
    "type": "კამერის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Кріплення камери 24мм 35мм 6мм.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Кріплення камери 24мм 35мм 6мм.stl",
    "date": "2026-03-15",
    "description": "კამერის დასამაგრებლად საჭიროა დაბეჭდოთ ორი ცალი (მარცხენა და მარჯვენა იდენტური და სიმეტრიულია).\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PLA, შევსება: 75%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PLA",
    "walls": 4,
    "infill": "75%",
    "supports": "არა"
  },
  {
    "id": "scat-58",
    "title": "კამერის სამაგრი (F7)",
    "type": "კამერის სამაგრი",
    "frame": "F7",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/F7 Camera mount.webp",
    "downloadUrl": "https://stl.vtx.in.ua/F7 Camera mount.zip",
    "date": "2026-03-15",
    "description": "არქივში მოცემულია ფაილები 3D ბეჭდვისთვის; რეკომენდებულია TPU პლასტიკით დაბეჭდვა მაქსიმალური დარტყმაგამძლეობისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 30%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "30%",
    "supports": "არა"
  },
  {
    "id": "scat-59",
    "title": "კამერის სამაგრი (F10)",
    "type": "კამერის სამაგრი",
    "frame": "F10",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/F10 Camera mount.webp",
    "downloadUrl": "https://stl.vtx.in.ua/F10 Camera mount.zip",
    "date": "2026-03-15",
    "description": "არქივში მოთავსებულია ფაილები სახელწოდებაში 'TPU' პრეფიქსით — ეს არის ბეჭდვისთვის რეკომენდებული დრეკადი მასალა.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 30%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "30%",
    "supports": "არა"
  },
  {
    "id": "scat-60",
    "title": "კამერის მბრუნავი სამაგრი 19 მმ (VT40)",
    "type": "კამერის მბრუნავი სამაგრი",
    "frame": "VT40",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/camholder_povorot_WT40.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Кронштейн поворотної_WT40.zip",
    "date": "2026-03-15",
    "description": "არქივში მოცემულია მბრუნავი მექანიზმის რამდენიმე ცალკეული დეტალი მარტივი აწყობისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-61",
    "title": "VTX ანტენის დაგრძელებული სამაგრი (Mark4 V2)",
    "type": "VTX ანტენის სამაგრი",
    "frame": "Mark4 V2",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/m4v2_sma_5mm.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/FPV_ANT_mount/m4v2_sma_5mm.stl",
    "date": "2026-03-15",
    "description": "ავტორის მიერ შექმნილი ღია მოდელი FPV პილოტების საზოგადოებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-62",
    "title": "FPV დეტექტორის სამაგრი — Chuika 3",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/detector_holder_chuika_3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/detector_holder_chuika_3.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-63",
    "title": "FPV დეტექტორის სამაგრი — Chuika 3 (V2)",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/detector_holder_v2_chuika_3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/detector_holder_v2_chuika_3.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-64",
    "title": "FPV დეტექტორის სამაგრი — Chuika 3 (ალტერნატიული)",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Chuika_Holder_01.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Chuika_Holder_01.zip",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-65",
    "title": "FPV დეტექტორის ანტენების ფიქსატორი — Chuika 3",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/chuika_ant_fixer.webp",
    "downloadUrl": "https://stl.vtx.in.ua/chuika_ant_fixer.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-66",
    "title": "FPV დეტექტორის სამაგრი — WHOOVER 3.3",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/detector_holder_ WHOOVER_33.webp",
    "downloadUrl": "https://stl.vtx.in.ua/detector_holder_ WHOOVER_33.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-67",
    "title": "FPV დეტექტორის სამაგრი — HUNTER-3",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/detector_holder_hunter_3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/detector_holder_hunter_3.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-68",
    "title": "FPV დეტექტორის სამაგრი — HUNTER-3 (კომპაქტური)",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/HUNTER3_holder.webp",
    "downloadUrl": "https://stl.vtx.in.ua/HUNTER3_holder.step",
    "date": "2026-03-15",
    "description": "სტანდარტული ბეჭდვის პარამეტრები, საყრდენების (supports) გარეშე, 3 კედელი, შევსება 15%-დან 100%-მდე.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "supports": "არა"
  },
  {
    "id": "scat-69",
    "title": "FPV დეტექტორის სამაგრი — Dzyga (ძიგა)",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Dzyga_holder_v1.2.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Dzyga_holder_v1.2.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-70",
    "title": "FPV დეტექტორის სამაგრი — Teneta SkyLink",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/video teneta new.webp",
    "downloadUrl": "https://stl.vtx.in.ua/video teneta new.zip",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-71",
    "title": "FPV დეტექტორის სამაგრი — Prorok (პროროკი)",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/si_AutoHold_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/si_AutoHold.zip",
    "date": "2026-03-15",
    "description": "ასაწყობად საჭიროა HOCO CA76 სამაგრი, ორი ხრახნიანი თერმო-ჩანართი M3 D4.2 h3 და ორი M3x20 ხრახნი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-72",
    "title": "FPV დეტექტორის ანტენების ფიქსატორი — Prorok",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/si_AntHold.webp",
    "downloadUrl": "https://stl.vtx.in.ua/si_AntHold.STL",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-73",
    "title": "FPV დეტექტორის სამაგრი ავტომობილისთვის — Franek 3.0",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/franek_holder.webp",
    "downloadUrl": "https://stl.vtx.in.ua/franek_holder.step",
    "date": "2026-03-15",
    "description": "დეტექტორის კორპუსის სამაგრი და სპეციალური კრონშტეინი ავტომობილში დასამონტაჟებლად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-74",
    "title": "FPV დეტექტორის მონიტორის სამაგრი ავტომობილისთვის — Franek 3.0",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/franek_holder_display.webp",
    "downloadUrl": "https://stl.vtx.in.ua/franek_holder_display.step",
    "date": "2026-03-15",
    "description": "Franek 3.0 დეტექტორის მონიტორის სამაგრი და სამონტაჟო კრონშტეინი ავტომობილის სალონისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-75",
    "title": "FPV დეტექტორის ანტენების ფიქსატორი — HUNTER-3",
    "type": "FPV დეტექტორის სამაგრი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/antenna_fix_hunter3_pic1.webp",
    "downloadUrl": "https://stl.vtx.in.ua/antenna_fix_hunter3.stl",
    "date": "2026-03-15",
    "description": "მონტაჟამდე მოხსენით გამჭვირვალე სილიკონის დამცავი ანტენების სამაგრიდან.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 20%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "20%",
    "supports": "არა"
  },
  {
    "id": "scat-76",
    "title": "ძრავის როტორის ექსტრაქტორი",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Motor extractor.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Motor extractor.zip",
    "date": "2026-03-15",
    "description": "ასაწყობად საჭიროა: ჭანჭიკი M5x60, ქანჩი M5x8 (2 ცალი), ხრახნი M3x20 (4 ცალი), ქანჩი M3 (8 ცალი). M5 ქანჩები უნდა ჩაეპრესოს შემთბარ პლასტიკში (თერმოფენი იდეალურია).\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "35%",
    "supports": "არა"
  },
  {
    "id": "scat-77",
    "title": "19 მმ კამერის სამაგრი Eachine Cobra X VRX სლოტში",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/CobraX_PNB_cover_19mm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/CobraX_PNB_cover_19mm.stl",
    "date": "2026-03-15",
    "description": "მარტივი და ეფექტური გზა FPV მუზარადისგან/სათვალიდან და თერმოკამერისგან ღამის ხედვის სისტემის ასაწყობად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "კი"
  },
  {
    "id": "scat-78",
    "title": "22 მმ კამერის სამაგრი Eachine Cobra X VRX სლოტში",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/CobraX_PNB_cover_22mm.webp",
    "downloadUrl": "https://stl.vtx.in.ua/CobraX_PNB_cover_22mm.stl",
    "date": "2026-03-15",
    "description": "მარტივი და ეფექტური გზა FPV მუზარადისგან/სათვალიდან და თერმოკამერისგან ღამის ხედვის სისტემის ასაწყობად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 3, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 3,
    "infill": "35%",
    "supports": "კი"
  },
  {
    "id": "scat-79",
    "title": "კამერის სამაგრი Skyzone 04X ვენტილაციის სლოტში",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/skyzone_04x_fan_camera_mount.webp",
    "downloadUrl": "https://stl.vtx.in.ua/skyzone_04x_fan_camera_mount.zip",
    "date": "2026-03-15",
    "description": "თერმოვიზიული კამერის FPV სათვალეზე დასაკავშირებლად. არქივშია სამაგრები 19, 22 და 27 მმ კამერებისთვის. ასაწყობად საჭიროა M3x16 ხრახნი და ქანჩი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 20%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "20%",
    "supports": "არა"
  },
  {
    "id": "scat-80",
    "title": "თერმოკამერის კორპუსი SkyZone სათვალეებისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/vrx_cam_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/vrx_cam.zip",
    "date": "2026-03-15",
    "description": "თერმოვიზიული კამერის კორპუსი SkyZone FPV სათვალეზე დასამაგრებლად. დეტალური ინსტრუქცია მოცემულია არქივში.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PLA, შევსება: 100%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PLA",
    "walls": 5,
    "infill": "100%",
    "supports": "არა"
  },
  {
    "id": "scat-81",
    "title": "Walksnail Avatar VRX სამაგრი Skyzone 04X-ზე",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Walsnail holder rails.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Walsnail holder rails.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-82",
    "title": "FPV მონიტორის სადგამი (Eachine 7\")",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Screen holder v3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Screen holder v3.stl",
    "date": "2026-03-15",
    "description": "სადგამი Eachine 7'' და მსგავსი FPV მონიტორებისთვის სამუშაო მაგიდაზე ან საველე პირობებში გამოსაყენებლად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-83",
    "title": "გამონატანი მოდული სახმელეთო სადგურისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/barvinok_remote_tx_unit_assembled_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Barvinok_UGV_remote_control.zip",
    "date": "2026-03-15",
    "description": "სახმელეთო მართვის კომპლექსის გამონატანი მოდული. არქივში მოცემულია რამდენიმე ცალკეული კომპონენტი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-84",
    "title": "Caddx Eclipse 004SL (256) კამერის დამცავი კორპუსი",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Caddx eclipse 004SL cover v4.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Caddx eclipse 004SL cover v4.zip",
    "date": "2026-03-15",
    "description": "კომპლექტში დამატებით შედის ობიექტივის დამცავი ხუფი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-85",
    "title": "ბლინდაჟის სამეთვალყურეო კამერის სამაგრი",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/blindazhnik.webp",
    "downloadUrl": "https://stl.vtx.in.ua/blindazhnik.zip",
    "date": "2026-03-15",
    "description": "ტესტირებულია Foxeer VRX მოდულთან; უზრუნველყოფს სამეთვალყურეო ვიდეოგამოსახულების საიმედო მიღებას.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 100%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "100%",
    "supports": "კი"
  },
  {
    "id": "scat-86",
    "title": "სადენების დამხმარე ხელსაწყო დამცავ ბადეში (Snake Skin)",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/wire_pusher-v1.webp",
    "downloadUrl": "https://stl.vtx.in.ua/wire_pusher-v1.stl",
    "date": "2026-03-15",
    "description": "საყრდენების გარეშე ბეჭდვისთვის რეკომენდებულია ხაზების პარალელური განლაგება (OrcaSlicer-ში Z ღერძზე 135 გრადუსიანი მობრუნება).\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-87",
    "title": "სამონტაჟო ადაპტერი RX as TX (Geprc)",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/geprc_rxastx_assembled.webp",
    "downloadUrl": "https://stl.vtx.in.ua/RX-as-TX-JR-Bay-Modification-Kit_2024-12-21.zip",
    "date": "2026-03-15",
    "description": "Geprc-ის ოფიციალური მოდელი. არქივში შედის რამდენიმე ფაილი, მათ შორის PCB პლატის ნახაზები.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-88",
    "title": "The Eye of Bosch — 2 კამერის გამონატანი მოდული",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/The-eye-of-Bosch_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/The-eye-of-Bosch.zip",
    "date": "2026-03-15",
    "description": "სამეთვალყურეო პუნქტის გატანა ორ ანალოგურ კამერაზე (ან თერმოვიზორზე) 100+ მეტრზე ჩვეულებრივი CAT5 ქსელის კაბელით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-89",
    "title": "The Eye of Bosch 2.0 — მბრუნავი კამერის გამონატანი მოდული",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/eye2_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/eye2.zip",
    "date": "2026-03-15",
    "description": "სამეთვალყურეო პუნქტის გატანა მბრუნავი ანალოგური კამერით 100+ მეტრზე ჩვეულებრივი CAT5 ქსელის კაბელით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-90",
    "title": "The Eye of Bosch 2.0 — მოდიფიკაციის პაკეტი 2 კამერისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/eye2_mod1_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/eye2_mod1.zip",
    "date": "2026-03-15",
    "description": "ბეჭდვის ფაილები The Eye of Bosch სისტემის 2 კამერაზე მოდიფიკაციის პაკეტისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-91",
    "title": "სტეკის საიზოლაციო შუასადები (0.8 მმ)",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Stack spacer.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Stack spacer v1.stl",
    "date": "2026-03-15",
    "description": "თხელი საიზოლაციო შუასადები სტეკისთვის (0.8 მმ). იცავს ელექტრონიკას მექანიკური შეხებისგან და ვიბრაციისგან.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 2, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 2,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-92",
    "title": "ფეხების სამაგრი Matrice 4T-ისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "Matrice 4T",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/d241c.webp",
    "downloadUrl": "https://stl.vtx.in.ua/d241c.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-93",
    "title": "სამონტაჟო ადაპტერი 20x20 მმ-დან 25x25 მმ-ზე",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/20x20_to_25x25_slim_by_Stoolen.webp",
    "downloadUrl": "https://raw.githubusercontent.com/Pancronos/FPV-3D-print/main/Files%20for%20Others/20x20_to_25x25_slim%20by%20Stoolen.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-94",
    "title": "Type-C პორტის დამცავი ხუფი",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/usb_c_dust-cover.webp",
    "downloadUrl": "https://raw.githubusercontent.com/Pancronos/FPV-3D-print/main/Files%20for%20Others/usb_c_dust-cover.stl",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: TPU, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "TPU",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-95",
    "title": "სატესტო სტენდი 4 VRX მოდულისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/vrx_box_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/vrx_box.zip",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-96",
    "title": "შედუღების შაბლონი XT90 - 2x XT60 გადამყვანისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/XT90_to_XT60x2_soldering_template_preview.webp",
    "downloadUrl": "https://raw.githubusercontent.com/dmytr0/glory_to_ukraine/master/Other_staff/XT90_to_XT60x2/XT90_to_XT60x2_soldering_template.stl",
    "date": "2026-03-15",
    "description": "შაბლონი XT90 - 2x XT60 დენის გადამყვანის უსაფრთხო და ზუსტი შედუღებისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-97",
    "title": "დამცავი კორპუსი XT90 - 2x XT60 გადამყვანისთვის",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/XT90_to_XT60x2_case_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/XT90_to_XT60x2_case.zip",
    "date": "2026-03-15",
    "description": "დამცავი საიზოლაციო კორპუსი XT90 - 2x XT60 დენის გადამყვანის კვანძისთვის.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 3,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-98",
    "title": "RadioMaster Boxer-ის ელემენტის განყოფილების სახურავი",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_Boxer_case_cover.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_Boxer_case_cover.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-99",
    "title": "დამატებითი აკუმულატორის სამაგრი (Mavic 3)",
    "type": "სხვა აქსესუარი",
    "frame": "Mavic 3",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_dop_akb_mavic_3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_dop_akb_mavic_3.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-100",
    "title": "RTK მოდულის დამცავი ხუფი (Matrice 4T)",
    "type": "სხვა აქსესუარი",
    "frame": "Matrice 4T",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_RTK_placeholder_Matrice4T.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_RTK_placeholder_Matrice4T.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-101",
    "title": "წინა ფეხების სამაგრი (Matrice 4T)",
    "type": "სხვა აქსესუარი",
    "frame": "Matrice 4T",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_arfix_front_DJI_Matrice_4.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_arfix_front_DJI_Matrice_4.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-102",
    "title": "წინა ფეხების სამაგრი (Mavic 3 Pro)",
    "type": "სხვა აქსესუარი",
    "frame": "Mavic 3",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_armfix_front_left_Mavic3_PRO_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_armfix_front_Mavic3_PRO.zip",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-103",
    "title": "უკანა ფეხების სამაგრი (Mavic 3 Pro)",
    "type": "სხვა აქსესუარი",
    "frame": "Mavic 3",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_armfix_back_Mavic3_PRO_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_armfix_back_Mavic3_PRO.zip",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-104",
    "title": "ფეხების სამაგრი (Autel EVO 4T)",
    "type": "სხვა აქსესუარი",
    "frame": "Autel Evo 4T",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_armfix_Autel_Evo_4T.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_armfix_Autel_Evo_4T.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "25%",
    "supports": "კი"
  },
  {
    "id": "scat-105",
    "title": "პროპელერების დამცავი რგოლები 10\" (ინჩი)",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_prop_protect_10.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_prop_protect_10.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-106",
    "title": "პროპელერების დამცავი რგოლები 7\" (ინჩი)",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_prop_protect_7.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_prop_protect_7.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-107",
    "title": "Mavic 3-ის აკუმულატორის დამცავი ქეისი",
    "type": "სხვა აქსესუარი",
    "frame": "Mavic 3",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/pidor_bat_case_mavic3_body_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/pidor_bat_case_mavic3.zip",
    "date": "2026-03-15",
    "description": "⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-108",
    "title": "სადესანტო ფეხები DJI Matrice 4T / 4E",
    "type": "სადესანტო ფეხები",
    "frame": "Matrice 4T",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Matrice_4T-4E_back_assembly.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Matrice_4T-4E_legs.zip",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 25%, კედლები: 5, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 5,
    "infill": "25%",
    "supports": "არა"
  },
  {
    "id": "scat-109",
    "title": "Yagi ანტენის (12x12 მმ) სამაგრი ანძაზე (\"კრაბი\")",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/Antenna holder v4.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Antenna holder v4.stl",
    "date": "2026-03-15",
    "description": "ერგება 12 მმ პროფილის Yagi ანტენას. იძლევა ანტენის პოლარიზაციის შეცვლის საშუალებას. ანძაზე დასამაგრებლად გამოიყენება 'კრაბის' ტიპის მომჭერი 3/8'' ხრახნით.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 30%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "30%",
    "supports": "კი"
  },
  {
    "id": "scat-110",
    "title": "F10 ჩარჩოს სხივების დამცავი ბამპერები",
    "type": "სხვა აქსესუარი",
    "frame": "F10",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/arm protect 19mm_preview.webp",
    "downloadUrl": "https://stl.vtx.in.ua/Arm Protect.zip",
    "date": "2026-03-15",
    "description": "სრული შევსებით (100% Infill) ბეჭდვა TPU-ით. არქივშია 2 ვერსია: ერთი ზუსტი მორგებით, მეორე 0.5 მმ ღრიჭოთი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: TPU, შევსება: 100%, კედლები: 3, საყრდენები (Supports): არა.",
    "material": "TPU",
    "walls": 3,
    "infill": "100%",
    "supports": "არა"
  },
  {
    "id": "scat-111",
    "title": "დამატებითი აღჭურვილობის პლატფორმა (Matrice 4T)",
    "type": "სხვა აქსესუარი",
    "frame": "Matrice 4T",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/DJI_Matrice_4T_ext_platform.webp",
    "downloadUrl": "https://stl.vtx.in.ua/DJI_Matrice_4T_ext_platform.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "არა"
  },
  {
    "id": "scat-112",
    "title": "დამატებითი აკუმულატორის დამჭერი (Mavic 3)",
    "type": "სხვა აქსესუარი",
    "frame": "Mavic 3",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/dop akb mavic 3.webp",
    "downloadUrl": "https://stl.vtx.in.ua/dop akb mavic 3.stl",
    "date": "2026-03-15",
    "description": "პრაქტიკაში გამოცდილი, გამძლე 3D მოდელი.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 15%, კედლები: 4, საყრდენები (Supports): კი.",
    "material": "PETG",
    "walls": 4,
    "infill": "15%",
    "supports": "კი"
  },
  {
    "id": "scat-113",
    "title": "Air3f T-Bone ანტენის ფიქსატორი ანძაზე",
    "type": "სხვა აქსესუარი",
    "frame": "უნივერსალური",
    "author": "DronehubGe",
    "image": "https://stl.vtx.in.ua/pic/T-bone5_Crab_holder v2.webp",
    "downloadUrl": "https://stl.vtx.in.ua/T-bone5_Crab_holder v2.stl",
    "date": "2026-03-15",
    "description": "სპეციალური შუასადები-სამაგრი Air3f T-Bone გამონატანი ანტენის მოდულის ანძაზე დასაფიქსირებლად.\n\n⚙️ რეკომენდებული პარამეტრები: მასალა: PETG, შევსება: 35%, კედლები: 7, საყრდენები (Supports): არა.",
    "material": "PETG",
    "walls": 7,
    "infill": "35%",
    "supports": "არა"
  }
];
